'use strict'
const database = require('../utils/database')
const { stringIsAMatch, hashString, generateToken, validateToken } = require('../utils/index')

module.exports = async function (fastify, opts) {
  const log = fastify.log

  // --- GET USER PROFILE ---
  // this route should use the value from "req.userId" to make a query into the "user" table with said userId.
  // the response body should be include the following fields: user.email, user.username and user.token
  // example response:
  // {
  //   user: {
  //     email: 'waldo@gmail.com',
  //     username: 'waldo',
  //     token: '123456'
  //   }
  // }
  const users = {}; // Stocker les profils des utilisateurs en mémoire (à des fins de démonstration)

  fastify.route({
    url: '/api/user',
    method: 'GET',
    preHandler: validateToken,
    handler: async (req, reply) => {
      // add the route implementation here

          try {
            const userId = req.userId;
      
            if (users[userId]) {
              const userProfile = {
                email: users[userId].email,
                username: users[userId].username,
                token: users[userId].token
              };
              reply.code(200).send({ user: userProfile });
            } else {
              reply.code(404).send({ error: 'User not found' });
            }
          } catch (error) {
            console.error(error);
            reply.code(500).send({ error: 'An error occurred while retrieving the user profile' });
          }
        }
      });
    }

  // --- SIGN UP ---
  // this route should receive the following fields on the request body: user.username, user.email and user.password
  // using the previous mentioned fields, plus a token generated by the "generateToken" utility method and the hash of the password
  // obtained by using the "hashString" utility method sending the user.password as function parameter, a record should be inserted
  // into the "user" table
  // the response of the request should include: email, username and user's token
  // example response:
  // {
  //   user: {
  //     username: 'admin',
  //     email: 'admin@gmail.com',
  //     token: 'super secret'
  //   }
  // }
  // HINT: remember that all utility methods ( hashString and generateToken ) are asynchronous functions! they need to be used with "await"
  fastify.route({
    url: '/api/users',
    method: 'POST',
    handler: async (req, reply) => {
      // add the route implementation here

          try {
            const { username, email, password } = req.body;
      
            const token = await generateToken(username);
      
            const hashedPassword = await hashString(password);
      
            const newUser = {
              username: username,
              email: email,
              password: hashedPassword,
              token: token
            };
            await insertUser(newUser);
      
            reply.code(201).send({ user: { username, email, token } });
          } catch (error) {
            console.error(error);
            reply.code(500).send({ error: 'An error occurred during user registration' });
          }
        }
      });

  // --- LOGIN ---
  // this route should receive on the request body only two fields: user.email and user.password
  // the route should first retrieve the user from the database, filtering the SQL query by the email provided
  // once with the user retrieved, you should use the utility method "stringIsAMatch" to compare the password included in the 
  // request body with the password from the user in the database.
  // if the passwords are a match, the response of the request should include: email, user's token and username
  // example response on this case:
  // {
  //   user: {
  //     username: 'henry',
  //     token: '123456',
  //     email: 'henry@gmail.com'
  //   }
  // }
  // if the passwords are NOT a match, the response should have a status code 401 and
  // the request body should have a "message" field with the value "invalid credentials"
  // HINT: remember that all utility methods ( hashString and generateToken ) are asynchronous functions! they need to be used with "await"
  fastify.post('/api/users/login', async function (req, reply) {
    // add the route implementation here
    const { email, password } = req.body.user
    const user = await database('user').where({ email }).first()
    const equal = await stringIsAMatch(password, user.password)
    if (!equal) {
      reply.status(401)
      return {
        message: 'Invalid credentials'
      }
    }
      try {
        const { email, password } = req.body.user;
    
        const user = await fastify.mysql.query('SELECT * FROM user WHERE email = ?', [email]);
    
        if (user.length === 0) {
          reply.status(401).send({ message: 'Invalid identifiers' });
          return;
        }
    
        const passwordMatch = await stringIsAMatch(password, user[0].password);
    
        if (!passwordMatch) {
          reply.status(401).send({ message: 'Invalid identifiers' });
          return;
        }
    
        const token = await generateToken(user[0].username);
    
        reply.status(200).send({
          user: {
            username: user[0].username,
            email: user[0].email,
            token: token
          }
        });

    return {
      user: {
        username: user.username,
        token: user.token,
        email: user.email,
      }
    }
  } catch (error) {
    console.error(error);
    reply.status(500).send({ message: 'An error occurred while connecting' });
  }
});

  // --- do not modify ---
  fastify.put('/api/user', async (req, reply) => req.body)
  // --- do not modify ---
  fastify.get('/api/profiles/:username', async (req, reply) => {
    const user = await database('user').select(['username', 'bio', 'image']).where({ username: req.params.username }).first()
    return {
      profile: user
    }
  })
